language: cpp
# Compiler selection
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Install lcov 1.11
  - wget http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz
  - tar -xvf lcov-1.13.tar.gz
  - cd lcov-1.13 && sudo make install
  - cd ..

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

# Build steps
script:
  - mkdir build
  - cd build
  - make -C ../test 
  - make -C ../test clean

after_success: 
- bash <(curl -s https://codecov.io/bash)

#instructions here: https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
## matrix:
##   include:
##     - compiler: gcc
##       addons:
##         apt:
##           sources:
##             - ubuntu-toolchain-r-test
##           packages:
##             - g++-4.9
##       env: COMPILER=g++-4.9
##     - compiler: gcc
##       addons:
##         apt:
##           sources:
##             - ubuntu-toolchain-r-test
##           packages:
##             - g++-5
##       env: COMPILER=g++-5
##     - compiler: clang
##       addons:
##         apt:
##           sources:
##             - ubuntu-toolchain-r-test
##             - llvm-toolchain-precise-3.6
##           packages:
##             - clang-3.6
##       env: COMPILER=clang++-3.6
##     - compiler: clang
##       addons:
##         apt:
##           sources:
##             - ubuntu-toolchain-r-test
##             - llvm-toolchain-precise-3.7
##           packages:
##             - clang-3.7
##       env: COMPILER=clang++-3.7
